One hundred small files in parallel echo4 port 1819 size 8000:

real	0m5,404s
user	0m0,000s
sys	0m0,042s
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m5,991s
user	0m0,019s
sys	0m0,032s

real	0m5,998s
user	0m0,040s
sys	0m0,016s

real	0m5,766s
user	0m0,028s
sys	0m0,025s

real	0m6,100s
user	0m0,011s
sys	0m0,035s

real	0m6,252s
user	0m0,032s
sys	0m0,037s

real	0m4,646s
user	0m0,020s
sys	0m0,028s

real	0m5,927s
user	0m0,015s
sys	0m0,033s

real	0m6,468s
user	0m0,025s
sys	0m0,038s

real	0m5,326s
user	0m0,043s
sys	0m0,000s

real	0m5,863s
user	0m0,032s
sys	0m0,016s

real	0m6,649s
user	0m0,019s
sys	0m0,019s

real	0m4,867s
user	0m0,018s
sys	0m0,027s

real	0m5,027s
user	0m0,025s
sys	0m0,040s
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m5,954s
user	0m0,016s
sys	0m0,029s

real	0m5,843s
user	0m0,028s
sys	0m0,026s

real	0m7,115s
user	0m0,022s
sys	0m0,032s

real	0m7,173s
user	0m0,029s
sys	0m0,017s

real	0m7,041s
user	0m0,021s
sys	0m0,017s

real	0m7,940s
user	0m0,053s
sys	0m0,024s

real	0m6,648s
user	0m0,025s
sys	0m0,017s
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m8,851s
user	0m0,019s
sys	0m0,032s

real	0m9,016s
user	0m0,014s
sys	0m0,040s

real	0m8,195s
user	0m0,023s
sys	0m0,051s

real	0m7,798s
user	0m0,018s
sys	0m0,059s

real	0m9,565s
user	0m0,038s
sys	0m0,076s

real	0m9,791s
user	0m0,037s
sys	0m0,020s

real	0m9,883s
user	0m0,032s
sys	0m0,021s

real	0m9,679s
user	0m0,035s
sys	0m0,027s

real	0m10,074s
user	0m0,025s
sys	0m0,059s

real	0m10,151s
user	0m0,034s
sys	0m0,071s
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m9,641s
user	0m0,037s
sys	0m0,029s
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m10,656s
user	0m0,039s
sys	0m0,025s

real	0m10,725s
user	0m0,048s
sys	0m0,037s
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in thread Thread-1 (Rdr):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pss/Escritorio/repos/Redes/T1/shell_scripts/../client_bw.py", line 12, in Rdr
    data=s.recv(read_write_size)
         ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

real	0m11,140s
user	0m0,034s
sys	0m0,028s

real	0m10,620s
user	0m0,034s
sys	0m0,034s

real	0m11,561s
user	0m0,032s
sys	0m0,059s

real	0m11,491s
user	0m0,043s
sys	0m0,036s

real	0m11,753s
user	0m0,026s
sys	0m0,038s

real	0m11,851s
user	0m0,030s
sys	0m0,039s

real	0m11,877s
user	0m0,013s
sys	0m0,046s

real	0m11,917s
user	0m0,032s
sys	0m0,019s

real	0m11,997s
user	0m0,037s
sys	0m0,007s

real	0m12,038s
user	0m0,033s
sys	0m0,038s

real	0m11,815s
user	0m0,050s
sys	0m0,007s

real	0m12,133s
user	0m0,019s
sys	0m0,043s

real	0m12,101s
user	0m0,030s
sys	0m0,044s

real	0m12,342s
user	0m0,026s
sys	0m0,053s

real	0m12,587s
user	0m0,017s
sys	0m0,040s

real	0m12,944s
user	0m0,033s
sys	0m0,026s

real	0m12,258s
user	0m0,028s
sys	0m0,031s

real	0m12,049s
user	0m0,027s
sys	0m0,018s

real	0m12,344s
user	0m0,027s
sys	0m0,017s

real	0m13,151s
user	0m0,027s
sys	0m0,021s

real	0m12,034s
user	0m0,017s
sys	0m0,040s

real	0m12,866s
user	0m0,028s
sys	0m0,040s

real	0m13,401s
user	0m0,026s
sys	0m0,036s

real	0m11,824s
user	0m0,026s
sys	0m0,024s

real	0m12,471s
user	0m0,020s
sys	0m0,045s

real	0m12,497s
user	0m0,023s
sys	0m0,031s

real	0m12,628s
user	0m0,014s
sys	0m0,045s

real	0m12,080s
user	0m0,043s
sys	0m0,000s

real	0m12,965s
user	0m0,025s
sys	0m0,023s

real	0m12,399s
user	0m0,024s
sys	0m0,018s

real	0m11,980s
user	0m0,027s
sys	0m0,013s

real	0m13,862s
user	0m0,030s
sys	0m0,015s

real	0m13,843s
user	0m0,023s
sys	0m0,036s

real	0m13,862s
user	0m0,031s
sys	0m0,034s

real	0m13,908s
user	0m0,031s
sys	0m0,018s

real	0m12,627s
user	0m0,041s
sys	0m0,016s

real	0m13,025s
user	0m0,025s
sys	0m0,028s

real	0m13,077s
user	0m0,048s
sys	0m0,055s

real	0m13,225s
user	0m0,032s
sys	0m0,037s

real	0m14,679s
user	0m0,044s
sys	0m0,029s

real	0m20,254s
user	0m0,023s
sys	0m0,028s

real	0m19,484s
user	0m0,032s
sys	0m0,026s

real	0m20,259s
user	0m0,023s
sys	0m0,017s

real	0m20,244s
user	0m0,024s
sys	0m0,034s

real	0m20,331s
user	0m0,021s
sys	0m0,017s

real	0m20,524s
user	0m0,023s
sys	0m0,018s

real	0m21,032s
user	0m0,026s
sys	0m0,032s

real	0m21,049s
user	0m0,030s
sys	0m0,018s

real	0m21,263s
user	0m0,015s
sys	0m0,032s

real	0m19,630s
user	0m0,022s
sys	0m0,019s

real	0m21,286s
user	0m0,018s
sys	0m0,028s

real	0m21,291s
user	0m0,024s
sys	0m0,050s

real	0m19,782s
user	0m0,027s
sys	0m0,018s

real	0m20,418s
user	0m0,019s
sys	0m0,027s

real	0m20,258s
user	0m0,023s
sys	0m0,054s

real	0m21,273s
user	0m0,031s
sys	0m0,015s

real	0m20,727s
user	0m0,029s
sys	0m0,017s

real	0m20,875s
user	0m0,026s
sys	0m0,009s

real	0m20,966s
user	0m0,020s
sys	0m0,024s

real	0m20,929s
user	0m0,028s
sys	0m0,024s

real	0m20,511s
user	0m0,028s
sys	0m0,014s

real	0m20,057s
user	0m0,016s
sys	0m0,026s

real	0m21,021s
user	0m0,031s
sys	0m0,016s

real	0m21,344s
user	0m0,036s
sys	0m0,018s

real	0m22,009s
user	0m0,025s
sys	0m0,034s

real	0m21,351s
user	0m0,038s
sys	0m0,044s
